<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $hoodieCategory = Category::where('slug', 'hoodie')->first();
        $tshirtCategory = Category::where('slug', 't-shirt')->first();
        $jeansCategory = Category::where('slug', 'jeans')->first();
        $jacketCategory = Category::where('slug', 'jacket')->first();
        $knitwearCategory = Category::where('slug', 'knitwear')->first();
        $dressCategory = Category::where('slug', 'dress')->first();
        $skirtCategory = Category::where('slug', 'skirt')->first();
        $sweaterCategory = Category::where('slug', 'sweater')->first();

        $products = [
            // HOODIES - 6 products
            [
                'category_id' => $hoodieCategory->id,
                'name' => 'Vintage Nike Hoodie Black',
                'price' => 150000,
                'description' => 'Hoodie Nike vintage dalam kondisi sangat baik. Warna hitam dengan logo classic Nike.',
                'condition' => 'Like New',
                'size' => 'L',
                'image_url' => 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500',
                'stock' => 5,
                'status' => 'available',
            ],
            [
                'category_id' => $hoodieCategory->id,
                'name' => 'Champion Reverse Weave Hoodie',
                'price' => 200000,
                'description' => 'Hoodie Champion Reverse Weave original. Bahan tebal dan nyaman.',
                'condition' => 'Good',
                'size' => 'M',
                'image_url' => 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=500',
                'stock' => 4,
                'status' => 'available',
            ],
            [
                'category_id' => $hoodieCategory->id,
                'name' => 'Adidas Trefoil Hoodie Grey',
                'price' => 175000,
                'description' => 'Hoodie Adidas dengan logo trefoil. Warna abu-abu muda.',
                'condition' => 'Like New',
                'size' => 'L',
                'image_url' => 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=500',
                'stock' => 3,
                'status' => 'available',
            ],
            [
                'category_id' => $hoodieCategory->id,
                'name' => 'Supreme Hoodie Red',
                'price' => 250000,
                'description' => 'Hoodie Supreme merah original. Desain minimalis dengan logo besar.',
                'condition' => 'Good',
                'size' => 'M',
                'image_url' => 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500',
                'stock' => 2,
                'status' => 'available',
            ],
            [
                'category_id' => $hoodieCategory->id,
                'name' => 'Carhartt Hoodie Navy',
                'price' => 180000,
                'description' => 'Hoodie Carhartt warna navy. Bahan tebal dan tahan lama.',
                'condition' => 'Good',
                'size' => 'XL',
                'image_url' => 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=500',
                'stock' => 6,
                'status' => 'available',
            ],
            [
                'category_id' => $hoodieCategory->id,
                'name' => 'Stüssy Hoodie Cream',
                'price' => 195000,
                'description' => 'Hoodie Stüssy warna cream. Kondisi seperti baru.',
                'condition' => 'Like New',
                'size' => 'L',
                'image_url' => 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500',
                'stock' => 4,
                'status' => 'available',
            ],
            
            // T-SHIRTS - 6 products
            [
                'category_id' => $tshirtCategory->id,
                'name' => 'Vintage Band Tee Pink Floyd',
                'price' => 85000,
                'description' => 'T-shirt band vintage Pink Floyd dengan desain retro. Kondisi sangat bagus.',
                'condition' => 'Good',
                'size' => 'M',
                'image_url' => 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500',
                'stock' => 7,
                'status' => 'available',
            ],
            [
                'category_id' => $tshirtCategory->id,
                'name' => 'Oversized Plain Tee Cream',
                'price' => 65000,
                'description' => 'T-shirt oversized polos warna cream. Bahan cotton combed berkualitas.',
                'condition' => 'Like New',
                'size' => 'XL',
                'image_url' => 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=500',
                'stock' => 10,
                'status' => 'available',
            ],
            [
                'category_id' => $tshirtCategory->id,
                'name' => 'Pokemon Pikachu Tee Yellow',
                'price' => 75000,
                'description' => 'T-shirt dengan karakter Pokemon Pikachu. Warna kuning cerah.',
                'condition' => 'Like New',
                'size' => 'L',
                'image_url' => 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500',
                'stock' => 8,
                'status' => 'available',
            ],
            [
                'category_id' => $tshirtCategory->id,
                'name' => 'Supreme Box Logo Tee Black',
                'price' => 120000,
                'description' => 'T-shirt Supreme dengan box logo. Warna hitam.',
                'condition' => 'Good',
                'size' => 'M',
                'image_url' => 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=500',
                'stock' => 3,
                'status' => 'available',
            ],
            [
                'category_id' => $tshirtCategory->id,
                'name' => 'Nike Swoosh Tee White',
                'price' => 95000,
                'description' => 'T-shirt Nike dengan logo swoosh. Warna putih bersih.',
                'condition' => 'Like New',
                'size' => 'L',
                'image_url' => 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500',
                'stock' => 9,
                'status' => 'available',
            ],
            [
                'category_id' => $tshirtCategory->id,
                'name' => 'Vintage Levis Tee',
                'price' => 80000,
                'description' => 'T-shirt Levis vintage dengan wash natural. Bahan tebal.',
                'condition' => 'Good',
                'size' => 'M',
                'image_url' => 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=500',
                'stock' => 6,
                'status' => 'available',
            ],

            // JEANS - 6 products
            [
                'category_id' => $jeansCategory->id,
                'name' => 'Levis 501 Original Blue',
                'price' => 250000,
                'description' => 'Celana jeans Levis 501 original. Classic fit, warna blue denim.',
                'condition' => 'Good',
                'size' => '32',
                'image_url' => 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=500',
                'stock' => 4,
                'status' => 'available',
            ],
            [
                'category_id' => $jeansCategory->id,
                'name' => 'Wrangler Denim Black',
                'price' => 220000,
                'description' => 'Celana jeans Wrangler warna hitam. Bahan denim tebal.',
                'condition' => 'Like New',
                'size' => '34',
                'image_url' => 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=500',
                'stock' => 5,
                'status' => 'available',
            ],
            [
                'category_id' => $jeansCategory->id,
                'name' => 'Gap Skinny Jeans Blue',
                'price' => 185000,
                'description' => 'Celana jeans Gap model skinny. Warna biru cerah.',
                'condition' => 'Good',
                'size' => '30',
                'image_url' => 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=500',
                'stock' => 6,
                'status' => 'available',
            ],
            [
                'category_id' => $jeansCategory->id,
                'name' => 'Diesel Jeans Dark Indigo',
                'price' => 290000,
                'description' => 'Celana jeans Diesel dark indigo. Kualitas premium.',
                'condition' => 'Good',
                'size' => '32',
                'image_url' => 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=500',
                'stock' => 3,
                'status' => 'available',
            ],
            [
                'category_id' => $jeansCategory->id,
                'name' => 'Zara Straight Jeans',
                'price' => 195000,
                'description' => 'Celana jeans Zara model straight. Fit nyaman untuk sehari-hari.',
                'condition' => 'Like New',
                'size' => '31',
                'image_url' => 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=500',
                'stock' => 7,
                'status' => 'available',
            ],
            [
                'category_id' => $jeansCategory->id,
                'name' => 'Topshop Jamie Jeans',
                'price' => 175000,
                'description' => 'Celana jeans Topshop model Jamie. Fit mulus dan pas.',
                'condition' => 'Good',
                'size' => '28',
                'image_url' => 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=500',
                'stock' => 5,
                'status' => 'available',
            ],

            // JACKETS - 6 products
            [
                'category_id' => $jacketCategory->id,
                'name' => 'Denim Jacket Vintage Blue',
                'price' => 180000,
                'description' => 'Jaket denim vintage dengan wash yang natural. Fit classic.',
                'condition' => 'Good',
                'size' => 'M',
                'image_url' => 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500',
                'stock' => 4,
                'status' => 'available',
            ],
            [
                'category_id' => $jacketCategory->id,
                'name' => 'Bomber Jacket Black',
                'price' => 220000,
                'description' => 'Jaket bomber warna hitam. Bahan parasut berkualitas tinggi.',
                'condition' => 'Like New',
                'size' => 'L',
                'image_url' => 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=500',
                'stock' => 6,
                'status' => 'available',
            ],
            [
                'category_id' => $jacketCategory->id,
                'name' => 'Leather Jacket Brown',
                'price' => 350000,
                'description' => 'Jaket kulit coklat asli. Desain klasik dan elegan.',
                'condition' => 'Good',
                'size' => 'L',
                'image_url' => 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500',
                'stock' => 2,
                'status' => 'available',
            ],
            [
                'category_id' => $jacketCategory->id,
                'name' => 'Wind Breaker Navy',
                'price' => 140000,
                'description' => 'Jaket wind breaker warna navy. Ringan dan tahan air.',
                'condition' => 'Like New',
                'size' => 'M',
                'image_url' => 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=500',
                'stock' => 8,
                'status' => 'available',
            ],
            [
                'category_id' => $jacketCategory->id,
                'name' => 'Puffer Jacket White',
                'price' => 280000,
                'description' => 'Jaket puffer putih penghanang panas. Sangat hangat.',
                'condition' => 'Good',
                'size' => 'L',
                'image_url' => 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500',
                'stock' => 5,
                'status' => 'available',
            ],
            [
                'category_id' => $jacketCategory->id,
                'name' => 'Oversized Blazer Grey',
                'price' => 260000,
                'description' => 'Blazer oversized warna abu-abu. Cocok untuk formal atau casual.',
                'condition' => 'Like New',
                'size' => 'XL',
                'image_url' => 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=500',
                'stock' => 4,
                'status' => 'available',
            ],

            // KNITWEAR - 5 products
            [
                'category_id' => $knitwearCategory->id ?? 1,
                'name' => 'Cable Knit Sweater Cream',
                'price' => 200000,
                'description' => 'Sweater rajutan dengan pola kabel. Warna cream hangat.',
                'condition' => 'Like New',
                'size' => 'M',
                'image_url' => 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=500',
                'stock' => 4,
                'status' => 'available',
            ],
            [
                'category_id' => $knitwearCategory->id ?? 1,
                'name' => 'Wool Blend Cardigan Navy',
                'price' => 220000,
                'description' => 'Kardigan campuran wool warna navy. Premium dan hangat.',
                'condition' => 'Good',
                'size' => 'L',
                'image_url' => 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=500',
                'stock' => 5,
                'status' => 'available',
            ],
            [
                'category_id' => $knitwearCategory->id ?? 1,
                'name' => 'Chunky Knit Sweater Beige',
                'price' => 185000,
                'description' => 'Sweater rajutan tebal warna beige. Cozy dan nyaman.',
                'condition' => 'Like New',
                'size' => 'L',
                'image_url' => 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=500',
                'stock' => 6,
                'status' => 'available',
            ],
            [
                'category_id' => $knitwearCategory->id ?? 1,
                'name' => 'Polo Neck Knit Black',
                'price' => 160000,
                'description' => 'Sweater polo neck warna hitam. Cocok untuk formal.',
                'condition' => 'Good',
                'size' => 'M',
                'image_url' => 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=500',
                'stock' => 4,
                'status' => 'available',
            ],
            [
                'category_id' => $knitwearCategory->id ?? 1,
                'name' => 'V-Neck Sweater Burgundy',
                'price' => 175000,
                'description' => 'Sweater V-neck warna burgundy. Elegant dan sophisticated.',
                'condition' => 'Like New',
                'size' => 'L',
                'image_url' => 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=500',
                'stock' => 5,
                'status' => 'available',
            ],

            // DRESS - 5 products
            [
                'category_id' => $dressCategory->id ?? 1,
                'name' => 'Little Black Dress Classic',
                'price' => 280000,
                'description' => 'Gaun hitam klasik untuk acara formal. Sempurna dan elegan.',
                'condition' => 'Like New',
                'size' => 'S',
                'image_url' => 'https://images.unsplash.com/photo-1595777707802-7b12b7e0b5a0?w=500',
                'stock' => 3,
                'status' => 'available',
            ],
            [
                'category_id' => $dressCategory->id ?? 1,
                'name' => 'Floral Summer Dress',
                'price' => 200000,
                'description' => 'Gaun musim panas dengan motif bunga. Fresh dan cantik.',
                'condition' => 'Good',
                'size' => 'M',
                'image_url' => 'https://images.unsplash.com/photo-1561128950-fc7658b76038?w=500',
                'stock' => 5,
                'status' => 'available',
            ],
            [
                'category_id' => $dressCategory->id ?? 1,
                'name' => 'Maxi Dress White',
                'price' => 250000,
                'description' => 'Maxi dress putih panjang. Cocok untuk pantai atau acara.',
                'condition' => 'Like New',
                'size' => 'M',
                'image_url' => 'https://images.unsplash.com/photo-1595777707802-7b12b7e0b5a0?w=500',
                'stock' => 4,
                'status' => 'available',
            ],
            [
                'category_id' => $dressCategory->id ?? 1,
                'name' => 'Cocktail Dress Red',
                'price' => 320000,
                'description' => 'Gaun koktail merah. Elegant dan glamor untuk pesta.',
                'condition' => 'Good',
                'size' => 'S',
                'image_url' => 'https://images.unsplash.com/photo-1561128950-fc7658b76038?w=500',
                'stock' => 2,
                'status' => 'available',
            ],
            [
                'category_id' => $dressCategory->id ?? 1,
                'name' => 'Casual Shift Dress Beige',
                'price' => 180000,
                'description' => 'Gaun shift kasual warna beige. Nyaman untuk sehari-hari.',
                'condition' => 'Like New',
                'size' => 'L',
                'image_url' => 'https://images.unsplash.com/photo-1595777707802-7b12b7e0b5a0?w=500',
                'stock' => 6,
                'status' => 'available',
            ],

            // SKIRT - 5 products
            [
                'category_id' => $skirtCategory->id ?? 1,
                'name' => 'Midi Skirt Navy',
                'price' => 160000,
                'description' => 'Rok midi warna navy. Nyaman dan penuh gaya.',
                'condition' => 'Like New',
                'size' => 'M',
                'image_url' => 'https://images.unsplash.com/photo-1598520027457-f7ba80f96dff?w=500',
                'stock' => 7,
                'status' => 'available',
            ],
            [
                'category_id' => $skirtCategory->id ?? 1,
                'name' => 'Denim Skirt Blue',
                'price' => 140000,
                'description' => 'Rok jeans biru. Casual dan fun untuk trendi.',
                'condition' => 'Good',
                'size' => 'S',
                'image_url' => 'https://images.unsplash.com/photo-1598520027457-f7ba80f96dff?w=500',
                'stock' => 8,
                'status' => 'available',
            ],
            [
                'category_id' => $skirtCategory->id ?? 1,
                'name' => 'Pleated Skirt Grey',
                'price' => 170000,
                'description' => 'Rok pleat warna abu-abu. Vintage dan cute.',
                'condition' => 'Like New',
                'size' => 'M',
                'image_url' => 'https://images.unsplash.com/photo-1598520027457-f7ba80f96dff?w=500',
                'stock' => 5,
                'status' => 'available',
            ],
            [
                'category_id' => $skirtCategory->id ?? 1,
                'name' => 'A-Line Skirt Black',
                'price' => 155000,
                'description' => 'Rok A-line hitam. Flatter dan elegan.',
                'condition' => 'Good',
                'size' => 'L',
                'image_url' => 'https://images.unsplash.com/photo-1598520027457-f7ba80f96dff?w=500',
                'stock' => 6,
                'status' => 'available',
            ],
            [
                'category_id' => $skirtCategory->id ?? 1,
                'name' => 'Maxi Skirt Floral',
                'price' => 200000,
                'description' => 'Rok panjang dengan motif bunga. Bohemian dan cantik.',
                'condition' => 'Like New',
                'size' => 'M',
                'image_url' => 'https://images.unsplash.com/photo-1598520027457-f7ba80f96dff?w=500',
                'stock' => 4,
                'status' => 'available',
            ],

            // SWEATER - 5 products
            [
                'category_id' => $sweaterCategory->id ?? 1,
                'name' => 'Cashmere Sweater Cream',
                'price' => 400000,
                'description' => 'Sweater cashmere warna cream. Super lembut dan premium.',
                'condition' => 'Like New',
                'size' => 'M',
                'image_url' => 'https://images.unsplash.com/photo-1563707902-45a084bb28ce?w=500',
                'stock' => 2,
                'status' => 'available',
            ],
            [
                'category_id' => $sweaterCategory->id ?? 1,
                'name' => 'Cotton Knit Sweater',
                'price' => 150000,
                'description' => 'Sweater cotton rajutan. Breathable dan tahan lama.',
                'condition' => 'Good',
                'size' => 'L',
                'image_url' => 'https://images.unsplash.com/photo-1563707902-45a084bb28ce?w=500',
                'stock' => 6,
                'status' => 'available',
            ],
            [
                'category_id' => $sweaterCategory->id ?? 1,
                'name' => 'Merino Wool Sweater Navy',
                'price' => 320000,
                'description' => 'Sweater wool merino warna navy. Hangat dan breathable.',
                'condition' => 'Like New',
                'size' => 'M',
                'image_url' => 'https://images.unsplash.com/photo-1563707902-45a084bb28ce?w=500',
                'stock' => 3,
                'status' => 'available',
            ],
            [
                'category_id' => $sweaterCategory->id ?? 1,
                'name' => 'Ribbed Sweater Black',
                'price' => 165000,
                'description' => 'Sweater dengan tekstur ribbed warna hitam. Fitted dan stylish.',
                'condition' => 'Good',
                'size' => 'S',
                'image_url' => 'https://images.unsplash.com/photo-1563707902-45a084bb28ce?w=500',
                'stock' => 5,
                'status' => 'available',
            ],
            [
                'category_id' => $sweaterCategory->id ?? 1,
                'name' => 'Oversized Sweater Camel',
                'price' => 210000,
                'description' => 'Sweater oversized warna camel. Comfy dan trendy.',
                'condition' => 'Like New',
                'size' => 'L',
                'image_url' => 'https://images.unsplash.com/photo-1563707902-45a084bb28ce?w=500',
                'stock' => 4,
                'status' => 'available',
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
